name: 06 – 3 - Contexts
on:
  workflow_dispatch:
    inputs:
      city:
        type: string
        default: Warsaw
run-name: 06 – Contexts | CITY – ${{ inputs.city }}

jobs:
  fetch_weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch weather
        run:  | 
          chmod +x ./06-context/pogoda/start.sh
          bash ./06-context/pogoda/start.sh ${{ inputs.city }} ${{ vars.weather_key }} >> $GITHUB_STEP_SUMMARY

      - name: Echo res
        run: echo "$GITHUB_STEP_SUMMARY"
